### ISSUE TITLE
Not working in Emacs 25.1

### ISSUE THREAD

**Issue by jiegec** [rolandwalker/simpleclip#5]
Using Mac OS X. Complains when installing: Warning(bytecomp): 'x-select-enable-clipboard' is an obsolete variable (as of 25.1); use 'select-enable-clipboard' instead. Using emacs git version under tmux using reattach-to-user-namespace. meta-c and simpleclip-copy do not work. Using pbcopy is ok. After reading the code, https://github.com/rolandwalker/simpleclip/blob/master/simpleclip.el#L359. I have tried invoking x-set-selection in _scratch_ buffer and eval, but nothing happened.

**Comment by jiegec** [comment]
But in the NEWS in Emacs 25, it says x-select-enable-clipboard now apply to all systems.

**Comment by rolandwalker** [comment]
Hi! Thanks! I don't have the latest pretest at the moment but will fix this as soon as I do.

**Comment by igrishaev** [comment]
I'm having the same troubles too, are there any updates?

**Comment by jiegec** [comment]
It's now working in my computer now. May require reattach-to-usernamespace under tmux.
