### ISSUE TITLE
Pasting utf-8 fails

### ISSUE THREAD

**Issue by thorstengrothe** [rolandwalker/simpleclip#9]
I love this package but it fails to paste utf-8 symbols from firefox for example.
This are my settings:

```
(x-select-enable-clipboard t)
(select-enable-clipboard t)
(set-language-environment "utf-8") 
(set-default-coding-systems 'utf-8) 
(set-selection-coding-system 'utf-8) 
```   
I always get strange symbols if I paste from clipboard manager in linux it works. How can I fix this?

Regards
Thorsten

**Comment by martinezhermes** [comment]
This is still an issue. Emojis for example don't copy over.

**Comment by thorstengrothe** [comment]
I'm on Linux here. I copied the first one from [from this website](http://xahlee.info/comp/unicode_emoticons.html) in the attached file. I works fine and emacs shows me the correct symbol. When I try the same with simpleclip I got `\u263a`.

[emoji_emacs.txt](https://github.com/rolandwalker/simpleclip/files/2275132/emoji_emacs.txt)

**Comment by rolandwalker** [comment]
Thanks!

I was able to duplicate this on Ubuntu and enter a fix in d179b45 .

The fix is not very sophisticated.  Instead of always assuming `UTF8_STRING`, it ought to try multiple types as in `gui--selection-value-internal` https://github.com/emacs-mirror/emacs/blob/2304bc9b9748db481ee1e5cff6f51709eb625394/lisp/select.el#L167-L181 .

**Comment by thorstengrothe** [comment]
Thanks for the fix.

**Comment by henrymazza** [comment]
I'm getting this on version 1.0.10. Am I doing something wrong? It pastes any non ASCII char like 'á' as something like `\207` and then an annoying prompt appears so I can choose another encoding but none seems to work:

```
These default coding systems were tried to encode text
in the buffer ‘TODOs.org’:
(utf-8-emacs-unix (821 . 4194200) (854 . 4194183) (957 . 4194194)) (utf-8-unix
                                                                    (821 . 4194200) (854 . 4194183) (957 . 4194194))
However, each of them encountered characters it couldn’t encode: 
utf-8-emacs-unix cannot encode these: \230 \207 \222
utf-8-unix cannot encode these: \230 \207 \222
```

**Comment by rolandwalker** [comment]
Hi!  What version of Emacs?
